### ISSUE TITLE
Update GH Actions PyPI publisher

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/ocha-anticipy#172]
Noticed this error in the GH actions logs: 

> Warning:  You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

**Comment by caldwellst** [comment]
Just noticed this issue when making `kalendar` so added this fix into my small PR #173, and then saw this, so should be addressed soon.

**Comment by caldwellst** [comment]
Closed by #173.
