### ISSUE TITLE
raster module set spatial dims

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/ocha-anticipy#183]
For the Yemen flooding work, I was using the raster `clip_box` function. However, I found that I had to set the spatial dims in `rio` first or else it wouldn't work, see the code [here](https://github.com/OCHA-DAP/pa-aa-yem-flooding/blob/main/src/datasource_extensions.py#L68-L71). 

Could the spatial dim setting be done when initializing `oap`?

**Comment by caldwellst** [comment]
Closed by #187
