### ISSUE TITLE
GloFAS forecast load

### ISSUE THREAD

**Issue by t-downing** [OCHA-DAP/ocha-anticipy#206]
When GloFAS forecasts are processed and saved, I think they aren't given a time dimension, so can't be concatenated by `xr.open_mfdataset` when calling `GlofasForecast.load()`

**Comment by turnerm** [comment]
Oops great catch, I was trying to take care of it using preprocessing but the time dim wasn't being propagated through, I've addressed it in #205

**Comment by t-downing** [comment]
Nicely dealt with in #205 , closing
